version: "3"
services:
  tor-gen:
    environment:
      ADDITIONAL_TORRC_CONFIG: |
        ORPort 9001
        DirPort 9030
        ExitPolicy reject *:*
        ExitPolicy reject6 *:*
        ExitRelay 1
        IPv6Exit 1
        Nickname ${TOR_RELAY_NICKNAME}
        ContactInfo ${TOR_RELAY_EMAIL}
  tor:
    ports: 
      - "9001"
      - "9030"

        